# Generated by Django 5.2.8 on 2025-11-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_bloqueoespacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nombre_entidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
