# Generated by Django 5.2.7 on 2025-11-11 21:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_configuracion', models.CharField(choices=[('MESA_U', 'Mesa en U'), ('AUDITORIO', 'Auditorio'), ('ESCUELA', 'Escuela'), ('BANQUETE', 'Banquete'), ('SOFA', 'Sofá'), ('CORTESIA', 'Cortesía'), ('MESA_12', 'Mesa de 12')], max_length=20)),
                ('capacidad', models.IntegerField(help_text='Capacidad máxima en esta configuración', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_socio_4h', models.DecimalField(decimal_places=2, help_text='Precio para socios (4 horas)', max_digits=10)),
                ('precio_socio_8h', models.DecimalField(blank=True, decimal_places=2, help_text='Precio para socios (8 horas)', max_digits=10, null=True)),
                ('precio_particular_4h', models.DecimalField(decimal_places=2, help_text='Precio para particulares (4 horas)', max_digits=10)),
                ('precio_particular_8h', models.DecimalField(blank=True, decimal_places=2, help_text='Precio para particulares (8 horas)', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Salón',
                'verbose_name_plural': 'Configuraciones de Salones',
                'ordering': ['salon__nombre', 'tipo_configuracion'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del salón')),
                ('imagen', models.CharField(blank=True, help_text='Ruta de la imagen del salón', max_length=200)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('tipo_cliente', models.CharField(choices=[('SOCIO', 'Socio'), ('PARTICULAR', 'Particular')], default='PARTICULAR', max_length=20)),
                ('fecha_evento', models.DateField()),
                ('duracion', models.CharField(choices=[('4H', '4 Horas'), ('8H', '8 Horas')], default='4H', max_length=2)),
                ('numero_personas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('configuracion_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.configuracionsalon')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_evento', '-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='configuracionsalon',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='reservas.salon'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionsalon',
            unique_together={('salon', 'tipo_configuracion')},
        ),
    ]
