# Generated by Django 5.2.7 on 2025-11-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsalon',
            name='tipo_configuracion',
            field=models.CharField(choices=[('MESA_U', 'Mesa en U'), ('AUDITORIO', 'Auditorio'), ('ESCUELA', 'Escuela'), ('BANQUETE', 'Banquete'), ('SOFA', 'Sofá'), ('CORTESIA', 'Cortesía'), ('MESA_12', 'Mesa de 12'), ('IMPERIAL', 'Imperial'), ('EMPRESARIAL', 'Empresarial')], max_length=20),
        ),
    ]
