# Generated by Django 5.2.8 on 2025-11-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_configuracionsalon_tipo_configuracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del socio', max_length=50, unique=True)),
                ('nombre_socio', models.CharField(help_text='Nombre del socio titular', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código de Socio',
                'verbose_name_plural': 'Códigos de Socios',
                'ordering': ['codigo'],
            },
        ),
    ]
