# Generated by Django 5.2.8 on 2025-11-20 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_codigosocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tiempo_decoracion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
