# Generated by Django 5.2.8 on 2025-11-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_hora_inicio_reserva_tiempo_decoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del bloqueo')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del bloqueo')),
                ('motivo', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('EVENTO_PRIVADO', 'Evento Privado'), ('REPARACION', 'Reparación'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del motivo del bloqueo')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, el bloqueo aplica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='reservas.salon')),
            ],
            options={
                'verbose_name': 'Bloqueo de Espacio',
                'verbose_name_plural': 'Bloqueos de Espacios',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
