# Generated by Django 5.2.8 on 2025-11-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_nombre_entidad'),
    ]

    operations = [
    ]
