# Generated by Django 5.2.7 on 2025-12-01 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_auto_20251120_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del servicio adicional', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del servicio')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10)),
                ('unidad_medida', models.CharField(default='Unidad', help_text='Ej: Persona, Mesa, Hora', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReservaServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de la reserva', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Cantidad × Precio unitario', max_digits=10)),
                ('notas', models.TextField(blank=True, help_text='Notas específicas para este servicio')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.servicioadicional')),
            ],
            options={
                'verbose_name': 'Servicio Adicional de Reserva',
                'verbose_name_plural': 'Servicios Adicionales de Reservas',
                'ordering': ['servicio__nombre'],
            },
        ),
    ]
