# Generated by Django 5.2.8 on 2025-12-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_servicioadicional_reservaservicioadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueoespacio',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Hora de fin (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='bloqueoespacio',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio (opcional)', null=True),
        ),
    ]
