# Generated by Django 5.2.7 on 2025-12-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_bloqueoespacio_hora_fin_bloqueoespacio_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosocio',
            name='celular',
            field=models.CharField(blank=True, help_text='Número de celular', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='codigosocio',
            name='email',
            field=models.EmailField(blank=True, help_text='Email del socio', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='codigosocio',
            name='identificacion',
            field=models.CharField(blank=True, help_text='Número de identificación / cédula', max_length=50, null=True),
        ),
    ]
