# Generated by Django 5.2.7 on 2025-12-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_codigosocio_celular_codigosocio_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosocio',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección del socio', max_length=250, null=True),
        ),
    ]
