# Generated by Django 5.2.7 on 2025-12-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_codigosocio_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('to_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Email / WhatsApp Log',
                'verbose_name_plural': 'Email / WhatsApp Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
