# Generated by Django 5.2.7 on 2025-12-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('to_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, help_text='Opcional: contenido HTML para email', null=True)),
                ('send_via', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('BOTH', 'Email + WhatsApp')], default='EMAIL', max_length=10)),
                ('sent', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación Manual',
                'verbose_name_plural': 'Notificaciones Manuales',
                'ordering': ['-created_at'],
            },
        ),
    ]
