# Generated by Django 5.2.7 on 2025-12-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_manualnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManualNotification',
        ),
    ]
