# Generated by Django 5.2.7 on 2025-12-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_delete_manualnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='to_phone',
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=20),
        ),
    ]
