# Generated by Django 5.2.7 on 2025-12-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_remove_emaillog_to_phone_alter_emaillog_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Log', 'verbose_name_plural': 'Email Logs'},
        ),
        migrations.AddField(
            model_name='codigosocio',
            name='empresa',
            field=models.CharField(blank=True, help_text='Empresa o entidad del socio (opcional)', max_length=200, null=True),
        ),
    ]
