# Generated by Django 5.2.7 on 2025-12-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_create_demo_asistente_user'),
        ('reservas', '0016_alter_emaillog_options_codigosocio_empresa'),
    ]

    operations = [
    ]
