# Generated by Django 6.0 on 2025-12-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_merge_20251207_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsalon',
            options={'ordering': ['salon__nombre', 'tipo_configuracion'], 'permissions': (('can_modify_prices', 'Puede modificar precios y parámetros del sistema'),), 'verbose_name': 'Configuración de Salón', 'verbose_name_plural': 'Configuraciones de Salones'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_evento', '-fecha_creacion'], 'permissions': (('can_review_reserva', 'Puede revisar reservas'), ('can_confirm_reserva', 'Puede confirmar reservas'), ('can_reject_reserva', 'Puede rechazar/cancelar reservas')), 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
