# Generated by Django 6.0 on 2026-03-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_alter_imagencomunicado_to_cloudinary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracionsalon',
            unique_together=set(),
        ),
    ]
