# Generated by Django 6.0 on 2026-03-29 22:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0024_alter_configuracionsalon_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioFlotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('enlace', models.URLField(blank=True, help_text='URL a abrir al hacer clic en el anuncio (opcional)', null=True)),
                ('mostrar_en_index', models.BooleanField(default=True, help_text='Si está activo para la página de inicio')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anuncio flotante',
                'verbose_name_plural': 'Anuncios flotantes',
                'ordering': ['-creado'],
            },
        ),
    ]
