# Generated by Django 6.0.4 on 2026-05-17 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0025_anuncioflotante'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsalon',
            name='capacidad_max',
            field=models.IntegerField(blank=True, help_text='Opcional. Si esta configuración admite un intervalo de personas (ej: 200–500), indica aquí el máximo. Déjalo vacío si la capacidad es un único valor.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracionsalon',
            name='capacidad',
            field=models.IntegerField(help_text='Capacidad (o capacidad mínima si se define un intervalo)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
