# Generated by Django 6.0.4 on 2026-06-03 04:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_configuracionsalon_capacidad_max_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenComunicado',
        ),
        migrations.AlterModelOptions(
            name='comunicado',
            options={'ordering': ['-publicado', '-id'], 'verbose_name': 'Comunicado', 'verbose_name_plural': 'Comunicados'},
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desactiva para ocultar del sitio sin borrar.'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='cuerpo',
            field=models.TextField(blank=True, help_text='Opcional. HTML basico permitido (negritas, parrafos, etc).'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='publicado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se publico. Si la dejas vacia el comunicado no aparecera ordenado por fecha.', null=True),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='titulo',
            field=models.CharField(blank=True, help_text='Opcional. Si lo dejas vacio el comunicado se mostrara solo con imagenes/cuerpo.', max_length=255),
        ),
        migrations.AlterField(
            model_name='comunicadoimagen',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='comunicadoimagen',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Posicion de la imagen dentro del comunicado (menor = primero).'),
        ),
    ]
